// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const deleteBudgetCategory = `-- name: DeleteBudgetCategory :exec
DELETE FROM budget_categories WHERE budget_id = $1 AND category_id = $2
`

type DeleteBudgetCategoryParams struct {
	BudgetID   uuid.UUID `json:"budget_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) DeleteBudgetCategory(ctx context.Context, arg DeleteBudgetCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteBudgetCategory, arg.BudgetID, arg.CategoryID)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, workspace_id, year, month, total_limit, created_at, updated_at FROM budgets WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Year,
		&i.Month,
		&i.TotalLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetByYearMonth = `-- name: GetBudgetByYearMonth :one
SELECT id, workspace_id, year, month, total_limit, created_at, updated_at FROM budgets
WHERE workspace_id = $1 AND year = $2 AND month = $3
`

type GetBudgetByYearMonthParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Year        int16     `json:"year"`
	Month       int16     `json:"month"`
}

func (q *Queries) GetBudgetByYearMonth(ctx context.Context, arg GetBudgetByYearMonthParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByYearMonth, arg.WorkspaceID, arg.Year, arg.Month)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Year,
		&i.Month,
		&i.TotalLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetCategorySpending = `-- name: GetBudgetCategorySpending :many
SELECT
    bc.category_id,
    bc.limit_amount,
    COALESCE(SUM(t.amount), 0)::float8 AS spent
FROM budget_categories bc
LEFT JOIN transactions t
    ON  t.category_id  = bc.category_id
    AND t.workspace_id = $2
    AND t.type         = 'expense'
    AND EXTRACT(YEAR  FROM t.date)::int = $3::int
    AND EXTRACT(MONTH FROM t.date)::int = $4::int
WHERE bc.budget_id = $1
GROUP BY bc.category_id, bc.limit_amount
`

type GetBudgetCategorySpendingParams struct {
	BudgetID    uuid.UUID `json:"budget_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Column3     int32     `json:"column_3"`
	Column4     int32     `json:"column_4"`
}

type GetBudgetCategorySpendingRow struct {
	CategoryID  uuid.UUID `json:"category_id"`
	LimitAmount float64   `json:"limit_amount"`
	Spent       float64   `json:"spent"`
}

func (q *Queries) GetBudgetCategorySpending(ctx context.Context, arg GetBudgetCategorySpendingParams) ([]GetBudgetCategorySpendingRow, error) {
	rows, err := q.db.Query(ctx, getBudgetCategorySpending,
		arg.BudgetID,
		arg.WorkspaceID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBudgetCategorySpendingRow{}
	for rows.Next() {
		var i GetBudgetCategorySpendingRow
		if err := rows.Scan(&i.CategoryID, &i.LimitAmount, &i.Spent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetCategories = `-- name: ListBudgetCategories :many
SELECT bc.budget_id, bc.category_id, bc.limit_amount, c.name AS category_name, c.icon AS category_icon
FROM budget_categories bc
JOIN categories c ON c.id = bc.category_id
WHERE bc.budget_id = $1
`

type ListBudgetCategoriesRow struct {
	BudgetID     uuid.UUID   `json:"budget_id"`
	CategoryID   uuid.UUID   `json:"category_id"`
	LimitAmount  float64     `json:"limit_amount"`
	CategoryName string      `json:"category_name"`
	CategoryIcon pgtype.Text `json:"category_icon"`
}

func (q *Queries) ListBudgetCategories(ctx context.Context, budgetID uuid.UUID) ([]ListBudgetCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listBudgetCategories, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetCategoriesRow{}
	for rows.Next() {
		var i ListBudgetCategoriesRow
		if err := rows.Scan(
			&i.BudgetID,
			&i.CategoryID,
			&i.LimitAmount,
			&i.CategoryName,
			&i.CategoryIcon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, workspace_id, year, month, total_limit, created_at, updated_at FROM budgets
WHERE workspace_id = $1
ORDER BY year DESC, month DESC
`

func (q *Queries) ListBudgets(ctx context.Context, workspaceID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Year,
			&i.Month,
			&i.TotalLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (workspace_id, year, month, total_limit)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, year, month)
DO UPDATE SET total_limit = EXCLUDED.total_limit, updated_at = NOW()
RETURNING id, workspace_id, year, month, total_limit, created_at, updated_at
`

type UpsertBudgetParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Year        int16     `json:"year"`
	Month       int16     `json:"month"`
	TotalLimit  float64   `json:"total_limit"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget,
		arg.WorkspaceID,
		arg.Year,
		arg.Month,
		arg.TotalLimit,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Year,
		&i.Month,
		&i.TotalLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBudgetCategory = `-- name: UpsertBudgetCategory :exec
INSERT INTO budget_categories (budget_id, category_id, limit_amount)
VALUES ($1, $2, $3)
ON CONFLICT (budget_id, category_id)
DO UPDATE SET limit_amount = EXCLUDED.limit_amount
`

type UpsertBudgetCategoryParams struct {
	BudgetID    uuid.UUID `json:"budget_id"`
	CategoryID  uuid.UUID `json:"category_id"`
	LimitAmount float64   `json:"limit_amount"`
}

func (q *Queries) UpsertBudgetCategory(ctx context.Context, arg UpsertBudgetCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertBudgetCategory, arg.BudgetID, arg.CategoryID, arg.LimitAmount)
	return err
}
