// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (workspace_id, name, icon, color, type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, icon, color, type, is_system, created_at
`

type CreateCategoryParams struct {
	WorkspaceID *uuid.UUID  `json:"workspace_id"`
	Name        string      `json:"name"`
	Icon        pgtype.Text `json:"icon"`
	Color       pgtype.Text `json:"color"`
	Type        string      `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.WorkspaceID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1 AND workspace_id IS NOT NULL AND workspace_id = $2
`

type DeleteCategoryParams struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.WorkspaceID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, workspace_id, name, icon, color, type, is_system, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listCategoriesForWorkspace = `-- name: ListCategoriesForWorkspace :many
SELECT id, workspace_id, name, icon, color, type, is_system, created_at FROM categories
WHERE workspace_id IS NULL OR workspace_id = $1
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListCategoriesForWorkspace(ctx context.Context, workspaceID *uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.Type,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $2, icon = $3, color = $4, type = $5
WHERE id = $1 AND workspace_id IS NOT NULL
RETURNING id, workspace_id, name, icon, color, type, is_system, created_at
`

type UpdateCategoryParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	Icon  pgtype.Text `json:"icon"`
	Color pgtype.Text `json:"color"`
	Type  string      `json:"type"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.Type,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}
