// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (workspace_id, name, lender, principal, rate, rate_type, installments, first_payment_date, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, name, lender, principal, rate, rate_type, installments, first_payment_date, notes, created_at, updated_at
`

type CreateDebtParams struct {
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
	Name             string      `json:"name"`
	Lender           pgtype.Text `json:"lender"`
	Principal        float64     `json:"principal"`
	Rate             float64     `json:"rate"`
	RateType         string      `json:"rate_type"`
	Installments     int32       `json:"installments"`
	FirstPaymentDate pgtype.Date `json:"first_payment_date"`
	Notes            pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.WorkspaceID,
		arg.Name,
		arg.Lender,
		arg.Principal,
		arg.Rate,
		arg.RateType,
		arg.Installments,
		arg.FirstPaymentDate,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Lender,
		&i.Principal,
		&i.Rate,
		&i.RateType,
		&i.Installments,
		&i.FirstPaymentDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDebtPayment = `-- name: CreateDebtPayment :one
INSERT INTO debt_payments (debt_id, period, amount, paid_at, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, debt_id, period, amount, paid_at, notes, created_at
`

type CreateDebtPaymentParams struct {
	DebtID uuid.UUID   `json:"debt_id"`
	Period int32       `json:"period"`
	Amount float64     `json:"amount"`
	PaidAt pgtype.Date `json:"paid_at"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDebtPayment(ctx context.Context, arg CreateDebtPaymentParams) (DebtPayment, error) {
	row := q.db.QueryRow(ctx, createDebtPayment,
		arg.DebtID,
		arg.Period,
		arg.Amount,
		arg.PaidAt,
		arg.Notes,
	)
	var i DebtPayment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Period,
		&i.Amount,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDebt = `-- name: DeleteDebt :exec
DELETE FROM debts WHERE id = $1 AND workspace_id = $2
`

type DeleteDebtParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteDebt(ctx context.Context, arg DeleteDebtParams) error {
	_, err := q.db.Exec(ctx, deleteDebt, arg.ID, arg.WorkspaceID)
	return err
}

const deleteDebtPayment = `-- name: DeleteDebtPayment :exec
DELETE FROM debt_payments WHERE id = $1 AND debt_id = $2
`

type DeleteDebtPaymentParams struct {
	ID     uuid.UUID `json:"id"`
	DebtID uuid.UUID `json:"debt_id"`
}

func (q *Queries) DeleteDebtPayment(ctx context.Context, arg DeleteDebtPaymentParams) error {
	_, err := q.db.Exec(ctx, deleteDebtPayment, arg.ID, arg.DebtID)
	return err
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, workspace_id, name, lender, principal, rate, rate_type, installments, first_payment_date, notes, created_at, updated_at FROM debts WHERE id = $1
`

func (q *Queries) GetDebtByID(ctx context.Context, id uuid.UUID) (Debt, error) {
	row := q.db.QueryRow(ctx, getDebtByID, id)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Lender,
		&i.Principal,
		&i.Rate,
		&i.RateType,
		&i.Installments,
		&i.FirstPaymentDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDebtPayment = `-- name: GetDebtPayment :one
SELECT id, debt_id, period, amount, paid_at, notes, created_at FROM debt_payments WHERE id = $1
`

func (q *Queries) GetDebtPayment(ctx context.Context, id uuid.UUID) (DebtPayment, error) {
	row := q.db.QueryRow(ctx, getDebtPayment, id)
	var i DebtPayment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Period,
		&i.Amount,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listDebtPayments = `-- name: ListDebtPayments :many
SELECT id, debt_id, period, amount, paid_at, notes, created_at FROM debt_payments WHERE debt_id = $1 ORDER BY period ASC
`

func (q *Queries) ListDebtPayments(ctx context.Context, debtID uuid.UUID) ([]DebtPayment, error) {
	rows, err := q.db.Query(ctx, listDebtPayments, debtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DebtPayment{}
	for rows.Next() {
		var i DebtPayment
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Period,
			&i.Amount,
			&i.PaidAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebts = `-- name: ListDebts :many
SELECT id, workspace_id, name, lender, principal, rate, rate_type, installments, first_payment_date, notes, created_at, updated_at FROM debts WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDebts(ctx context.Context, workspaceID uuid.UUID) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebts, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Debt{}
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Lender,
			&i.Principal,
			&i.Rate,
			&i.RateType,
			&i.Installments,
			&i.FirstPaymentDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :one
UPDATE debts
SET name               = $2,
    lender             = $3,
    principal          = $4,
    rate               = $5,
    rate_type          = $6,
    installments       = $7,
    first_payment_date = $8,
    notes              = $9,
    updated_at         = NOW()
WHERE id = $1 AND workspace_id = $10
RETURNING id, workspace_id, name, lender, principal, rate, rate_type, installments, first_payment_date, notes, created_at, updated_at
`

type UpdateDebtParams struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Lender           pgtype.Text `json:"lender"`
	Principal        float64     `json:"principal"`
	Rate             float64     `json:"rate"`
	RateType         string      `json:"rate_type"`
	Installments     int32       `json:"installments"`
	FirstPaymentDate pgtype.Date `json:"first_payment_date"`
	Notes            pgtype.Text `json:"notes"`
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebt,
		arg.ID,
		arg.Name,
		arg.Lender,
		arg.Principal,
		arg.Rate,
		arg.RateType,
		arg.Installments,
		arg.FirstPaymentDate,
		arg.Notes,
		arg.WorkspaceID,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Lender,
		&i.Principal,
		&i.Rate,
		&i.RateType,
		&i.Installments,
		&i.FirstPaymentDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDebtPayment = `-- name: UpdateDebtPayment :one
UPDATE debt_payments SET amount = $2, paid_at = $3, notes = $4
WHERE id = $1
RETURNING id, debt_id, period, amount, paid_at, notes, created_at
`

type UpdateDebtPaymentParams struct {
	ID     uuid.UUID   `json:"id"`
	Amount float64     `json:"amount"`
	PaidAt pgtype.Date `json:"paid_at"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateDebtPayment(ctx context.Context, arg UpdateDebtPaymentParams) (DebtPayment, error) {
	row := q.db.QueryRow(ctx, updateDebtPayment,
		arg.ID,
		arg.Amount,
		arg.PaidAt,
		arg.Notes,
	)
	var i DebtPayment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Period,
		&i.Amount,
		&i.PaidAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
