// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO workspace_invitations (workspace_id, email, role, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, email, role, token, status, invited_by, expires_at, created_at
`

type CreateInvitationParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	InvitedBy   uuid.UUID          `json:"invited_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, workspace_id, email, role, token, status, invited_by, expires_at, created_at FROM workspace_invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, workspace_id, email, role, token, status, invited_by, expires_at, created_at FROM workspace_invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token uuid.UUID) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, workspace_id, email, role, token, status, invited_by, expires_at, created_at FROM workspace_invitations
WHERE workspace_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitations(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvitation{}
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.Status,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE workspace_invitations SET status = $2 WHERE id = $1 RETURNING id, workspace_id, email, role, token, status, invited_by, expires_at, created_at
`

type UpdateInvitationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
