// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: savings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContribution = `-- name: CreateContribution :one
INSERT INTO savings_contributions (goal_id, amount, contributed_at, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, goal_id, amount, contributed_at, notes, created_at
`

type CreateContributionParams struct {
	GoalID        uuid.UUID   `json:"goal_id"`
	Amount        float64     `json:"amount"`
	ContributedAt pgtype.Date `json:"contributed_at"`
	Notes         pgtype.Text `json:"notes"`
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (SavingsContribution, error) {
	row := q.db.QueryRow(ctx, createContribution,
		arg.GoalID,
		arg.Amount,
		arg.ContributedAt,
		arg.Notes,
	)
	var i SavingsContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Amount,
		&i.ContributedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createSavingsGoal = `-- name: CreateSavingsGoal :one
INSERT INTO savings_goals (workspace_id, name, target_amount, deadline, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, name, target_amount, deadline, notes, created_at, updated_at
`

type CreateSavingsGoalParams struct {
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	Name         string      `json:"name"`
	TargetAmount float64     `json:"target_amount"`
	Deadline     pgtype.Date `json:"deadline"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) CreateSavingsGoal(ctx context.Context, arg CreateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, createSavingsGoal,
		arg.WorkspaceID,
		arg.Name,
		arg.TargetAmount,
		arg.Deadline,
		arg.Notes,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.TargetAmount,
		&i.Deadline,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContribution = `-- name: DeleteContribution :exec
DELETE FROM savings_contributions WHERE id = $1 AND goal_id = $2
`

type DeleteContributionParams struct {
	ID     uuid.UUID `json:"id"`
	GoalID uuid.UUID `json:"goal_id"`
}

func (q *Queries) DeleteContribution(ctx context.Context, arg DeleteContributionParams) error {
	_, err := q.db.Exec(ctx, deleteContribution, arg.ID, arg.GoalID)
	return err
}

const deleteSavingsGoal = `-- name: DeleteSavingsGoal :exec
DELETE FROM savings_goals WHERE id = $1 AND workspace_id = $2
`

type DeleteSavingsGoalParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteSavingsGoal(ctx context.Context, arg DeleteSavingsGoalParams) error {
	_, err := q.db.Exec(ctx, deleteSavingsGoal, arg.ID, arg.WorkspaceID)
	return err
}

const getContribution = `-- name: GetContribution :one
SELECT id, goal_id, amount, contributed_at, notes, created_at FROM savings_contributions WHERE id = $1
`

func (q *Queries) GetContribution(ctx context.Context, id uuid.UUID) (SavingsContribution, error) {
	row := q.db.QueryRow(ctx, getContribution, id)
	var i SavingsContribution
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Amount,
		&i.ContributedAt,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getSavingsGoalByID = `-- name: GetSavingsGoalByID :one
SELECT id, workspace_id, name, target_amount, deadline, notes, created_at, updated_at FROM savings_goals WHERE id = $1
`

func (q *Queries) GetSavingsGoalByID(ctx context.Context, id uuid.UUID) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, getSavingsGoalByID, id)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.TargetAmount,
		&i.Deadline,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalContributed = `-- name: GetTotalContributed :one
SELECT COALESCE(SUM(amount), 0)::float8 AS total FROM savings_contributions WHERE goal_id = $1
`

func (q *Queries) GetTotalContributed(ctx context.Context, goalID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalContributed, goalID)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const listContributions = `-- name: ListContributions :many
SELECT id, goal_id, amount, contributed_at, notes, created_at FROM savings_contributions
WHERE goal_id = $1
ORDER BY contributed_at DESC, created_at DESC
`

func (q *Queries) ListContributions(ctx context.Context, goalID uuid.UUID) ([]SavingsContribution, error) {
	rows, err := q.db.Query(ctx, listContributions, goalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsContribution{}
	for rows.Next() {
		var i SavingsContribution
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Amount,
			&i.ContributedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoals = `-- name: ListSavingsGoals :many
SELECT id, workspace_id, name, target_amount, deadline, notes, created_at, updated_at FROM savings_goals WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSavingsGoals(ctx context.Context, workspaceID uuid.UUID) ([]SavingsGoal, error) {
	rows, err := q.db.Query(ctx, listSavingsGoals, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavingsGoal{}
	for rows.Next() {
		var i SavingsGoal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.TargetAmount,
			&i.Deadline,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavingsGoalsWithProgress = `-- name: ListSavingsGoalsWithProgress :many
SELECT
    sg.id, sg.workspace_id, sg.name, sg.target_amount, sg.deadline, sg.notes, sg.created_at, sg.updated_at,
    COALESCE(SUM(sc.amount), 0)::float8 AS total_contributed
FROM savings_goals sg
LEFT JOIN savings_contributions sc ON sc.goal_id = sg.id
WHERE sg.workspace_id = $1
GROUP BY sg.id
ORDER BY sg.created_at DESC
`

type ListSavingsGoalsWithProgressRow struct {
	ID               uuid.UUID          `json:"id"`
	WorkspaceID      uuid.UUID          `json:"workspace_id"`
	Name             string             `json:"name"`
	TargetAmount     float64            `json:"target_amount"`
	Deadline         pgtype.Date        `json:"deadline"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	TotalContributed float64            `json:"total_contributed"`
}

func (q *Queries) ListSavingsGoalsWithProgress(ctx context.Context, workspaceID uuid.UUID) ([]ListSavingsGoalsWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listSavingsGoalsWithProgress, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavingsGoalsWithProgressRow{}
	for rows.Next() {
		var i ListSavingsGoalsWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.TargetAmount,
			&i.Deadline,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalContributed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSavingsGoal = `-- name: UpdateSavingsGoal :one
UPDATE savings_goals
SET name          = $2,
    target_amount = $3,
    deadline      = $4,
    notes         = $5,
    updated_at    = NOW()
WHERE id = $1 AND workspace_id = $6
RETURNING id, workspace_id, name, target_amount, deadline, notes, created_at, updated_at
`

type UpdateSavingsGoalParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	TargetAmount float64     `json:"target_amount"`
	Deadline     pgtype.Date `json:"deadline"`
	Notes        pgtype.Text `json:"notes"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) UpdateSavingsGoal(ctx context.Context, arg UpdateSavingsGoalParams) (SavingsGoal, error) {
	row := q.db.QueryRow(ctx, updateSavingsGoal,
		arg.ID,
		arg.Name,
		arg.TargetAmount,
		arg.Deadline,
		arg.Notes,
		arg.WorkspaceID,
	)
	var i SavingsGoal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.TargetAmount,
		&i.Deadline,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
