// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
WHERE workspace_id = $1
  AND ($2::date IS NULL OR date >= $2::date)
  AND ($3::date   IS NULL OR date <= $3::date)
  AND ($4::text   IS NULL OR type = $4::text)
  AND ($5::uuid IS NULL OR category_id = $5::uuid)
`

type CountTransactionsParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
	TxType      pgtype.Text `json:"tx_type"`
	CategoryID  *uuid.UUID  `json:"category_id"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.WorkspaceID,
		arg.DateFrom,
		arg.DateTo,
		arg.TxType,
		arg.CategoryID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (workspace_id, user_id, category_id, type, amount, description, date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, user_id, category_id, transfer_id, type, transfer_direction, amount, description, date, created_at, updated_at
`

type CreateTransactionParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	UserID      uuid.UUID   `json:"user_id"`
	CategoryID  *uuid.UUID  `json:"category_id"`
	Type        string      `json:"type"`
	Amount      float64     `json:"amount"`
	Description pgtype.Text `json:"description"`
	Date        pgtype.Date `json:"date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.WorkspaceID,
		arg.UserID,
		arg.CategoryID,
		arg.Type,
		arg.Amount,
		arg.Description,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.CategoryID,
		&i.TransferID,
		&i.Type,
		&i.TransferDirection,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransferRecord = `-- name: CreateTransferRecord :one
INSERT INTO transfers (from_workspace_id, to_workspace_id, note)
VALUES ($1, $2, $3)
RETURNING id, from_workspace_id, to_workspace_id, note, created_at
`

type CreateTransferRecordParams struct {
	FromWorkspaceID uuid.UUID   `json:"from_workspace_id"`
	ToWorkspaceID   uuid.UUID   `json:"to_workspace_id"`
	Note            pgtype.Text `json:"note"`
}

func (q *Queries) CreateTransferRecord(ctx context.Context, arg CreateTransferRecordParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransferRecord, arg.FromWorkspaceID, arg.ToWorkspaceID, arg.Note)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromWorkspaceID,
		&i.ToWorkspaceID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const createTransferTransaction = `-- name: CreateTransferTransaction :one
INSERT INTO transactions (workspace_id, user_id, transfer_id, type, transfer_direction, amount, description, date)
VALUES ($1, $2, $3, 'transfer', $4, $5, $6, $7)
RETURNING id, workspace_id, user_id, category_id, transfer_id, type, transfer_direction, amount, description, date, created_at, updated_at
`

type CreateTransferTransactionParams struct {
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	UserID            uuid.UUID   `json:"user_id"`
	TransferID        *uuid.UUID  `json:"transfer_id"`
	TransferDirection pgtype.Text `json:"transfer_direction"`
	Amount            float64     `json:"amount"`
	Description       pgtype.Text `json:"description"`
	Date              pgtype.Date `json:"date"`
}

func (q *Queries) CreateTransferTransaction(ctx context.Context, arg CreateTransferTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransferTransaction,
		arg.WorkspaceID,
		arg.UserID,
		arg.TransferID,
		arg.TransferDirection,
		arg.Amount,
		arg.Description,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.CategoryID,
		&i.TransferID,
		&i.Type,
		&i.TransferDirection,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND workspace_id = $2
`

type DeleteTransactionParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.WorkspaceID)
	return err
}

const getDailySummary = `-- name: GetDailySummary :many
SELECT
    date,
    SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END)::float8                                AS total_expense,
    SUM(CASE WHEN type = 'income'  THEN amount ELSE 0 END)::float8                                AS total_income,
    SUM(CASE WHEN type = 'transfer' AND transfer_direction = 'out' THEN amount ELSE 0 END)::float8 AS total_transfer_out,
    SUM(CASE WHEN type = 'transfer' AND transfer_direction = 'in'  THEN amount ELSE 0 END)::float8 AS total_transfer_in,
    COUNT(*)::int                                                                                   AS transaction_count
FROM transactions
WHERE workspace_id = $1
  AND ($4::date IS NULL OR date >= $4::date)
  AND ($5::date   IS NULL OR date <= $5::date)
GROUP BY date
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type GetDailySummaryParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
}

type GetDailySummaryRow struct {
	Date             pgtype.Date `json:"date"`
	TotalExpense     float64     `json:"total_expense"`
	TotalIncome      float64     `json:"total_income"`
	TotalTransferOut float64     `json:"total_transfer_out"`
	TotalTransferIn  float64     `json:"total_transfer_in"`
	TransactionCount int32       `json:"transaction_count"`
}

func (q *Queries) GetDailySummary(ctx context.Context, arg GetDailySummaryParams) ([]GetDailySummaryRow, error) {
	rows, err := q.db.Query(ctx, getDailySummary,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySummaryRow{}
	for rows.Next() {
		var i GetDailySummaryRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalExpense,
			&i.TotalIncome,
			&i.TotalTransferOut,
			&i.TotalTransferIn,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, workspace_id, user_id, category_id, transfer_id, type, transfer_direction, amount, description, date, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.CategoryID,
		&i.TransferID,
		&i.Type,
		&i.TransferDirection,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, workspace_id, user_id, category_id, transfer_id, type, transfer_direction, amount, description, date, created_at, updated_at FROM transactions
WHERE workspace_id = $1
  AND ($4::date IS NULL OR date >= $4::date)
  AND ($5::date   IS NULL OR date <= $5::date)
  AND ($6::text   IS NULL OR type = $6::text)
  AND ($7::uuid IS NULL OR category_id = $7::uuid)
ORDER BY date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	DateFrom    pgtype.Date `json:"date_from"`
	DateTo      pgtype.Date `json:"date_to"`
	TxType      pgtype.Text `json:"tx_type"`
	CategoryID  *uuid.UUID  `json:"category_id"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.WorkspaceID,
		arg.Limit,
		arg.Offset,
		arg.DateFrom,
		arg.DateTo,
		arg.TxType,
		arg.CategoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.CategoryID,
			&i.TransferID,
			&i.Type,
			&i.TransferDirection,
			&i.Amount,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateCursor = `-- name: ListTransactionsByDateCursor :many
SELECT id, workspace_id, user_id, category_id, transfer_id, type, transfer_direction, amount, description, date, created_at, updated_at FROM transactions
WHERE workspace_id = $1
  AND date = $2
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC
LIMIT $3
`

type ListTransactionsByDateCursorParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Date        pgtype.Date        `json:"date"`
	Limit       int32              `json:"limit"`
	Cursor      pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListTransactionsByDateCursor(ctx context.Context, arg ListTransactionsByDateCursorParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateCursor,
		arg.WorkspaceID,
		arg.Date,
		arg.Limit,
		arg.Cursor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.CategoryID,
			&i.TransferID,
			&i.Type,
			&i.TransferDirection,
			&i.Amount,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET category_id = $2, amount = $3, description = $4, date = $5, updated_at = NOW()
WHERE id = $1 AND type != 'transfer'
RETURNING id, workspace_id, user_id, category_id, transfer_id, type, transfer_direction, amount, description, date, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID          uuid.UUID   `json:"id"`
	CategoryID  *uuid.UUID  `json:"category_id"`
	Amount      float64     `json:"amount"`
	Description pgtype.Text `json:"description"`
	Date        pgtype.Date `json:"date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Date,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.CategoryID,
		&i.TransferID,
		&i.Type,
		&i.TransferDirection,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
